---
name: ğŸ³ CI Reusable Release

on:
  workflow_call:
    inputs:
      release-please-release-type:
        description: The release type for Release Please
        required: false
        default: simple
        type: string

jobs:
  release:
    name: ğŸ”– Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4.4.0
        id: release
        with:
          release-type: ${{ inputs.release-please-release-type }}
          skip-github-pull-request: true
