name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/ci-reusable-checks.yaml
    name: Lint and Secret detection
    permissions:
      contents: read
      packages: read
      statuses: write
    #uses: StaatsolieNV/workflows/.github/workflows/ci-reusable-checks.yaml@feat/initial-workflows
  
  test-and-release:
    uses: ./.github/workflows/ci-reusable-docker.yaml
    name: Build, Test and Release
    needs: [validate]
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      environment: 'development'
      pull-request: ${{ github.event_name == 'pull_request' }}
      acr-name: ${{ vars.ACR_NAME }}
      release-please-release-type: 'python'

  deploy-development:
    name: Deploy to Azure App Service Development
    if: needs.test-and-release.outputs.image-built-and-pushed == 'true'
    needs: [validate, test-and-release]
    secrets: inherit
    uses: ./.github/workflows/cd-reusable-webapp-deploy.yaml
    with:
      docker-image: ${{ needs.test-and-release.outputs.docker_image }}
      environment: 'development'
      webapp-name: ${{ vars.AZURE_WEBAPP_NAME_DEVELOPMENT }}
      
  deploy-production:
    name: Deploy to Azure App Service Production
    needs: [validate, test-and-release, deploy-development]
    secrets: inherit
    uses: ./.github/workflows/cd-reusable-webapp-deploy.yaml
    with:
      docker-image: ${{ needs.test-and-release.outputs.docker_image }}
      environment: 'production'
      webapp-name: ${{ vars.AZURE_WEBAPP_NAME_PRODUCTION }}