name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/ci-reusable-checks.yaml
    with:
      super-linter: false
    name: Lint and Secret detection
    permissions:
      contents: read
      packages: read
      statuses: write
  
  test:
    uses: ./.github/workflows/cicd-reusable-docker.yaml
    name: Run tests in Docker container
    with:
      target: test
  
  test-build:
    uses: ./.github/workflows/cicd-reusable-docker.yaml
    name: Test image build
    with:
      target: build
  