---
name: ðŸ³ CI Reusable Docker Build and Push Workflow with ACR support

on:
  workflow_call:
    inputs:
      push:
        description: Push the image to ACR
        required: false
        default: false
        type: boolean
      target:
        description: The target stage to build in the Dockerfile
        required: false
        type: string
      acr-name:
        description: The name of the Azure Container Registry
        required: false
        type: string
      tag:
        description: The tag to use for the Docker image
        required: false
        type: string
      labels:
        description: Labels to add to the Docker image
        required: false
        type: string

jobs:

  build-and-push:
    name: ðŸ“¦ Build Image and Push
    runs-on: ubuntu-24.04
    env:
      DOCKER_IMAGE: ${{ inputs.acr-name }}.azurecr.io/${{ github.repository }}:${{ inputs.tag }}
    outputs:
      # The image was built and pushed successfully
      docker-image: ${{ steps.validate-and-set-outputs.outputs.docker-image }}
    steps:
      - name: Validate Inputs and Set Outputs
        id: validate-and-set-outputs
        run: |
          echo "Inputs:"
          echo "  push: ${{ inputs.push }}"
          echo "  target: ${{ inputs.target }}"
          echo "  acr-name: ${{ inputs.acr-name }}"
          echo "  tag: ${{ inputs.tag }}"
          # If push is true, ensure acr-name  and tag are not empty
          if [ "${{ inputs.push }}" = "true" ] && [ -z "${{ inputs.acr-name }}" ] && [ -z "${{ inputs.tag }}" ]; then
            echo "Error: acr-name and tag are required when push is true"
            exit 1
          fi
          # Setup docker_image output based on inputs
          if [ "${{ inputs.push }}" = "true" ]; then
            echo "docker-image=${{ inputs.acr-name }}.azurecr.io/${{ github.repository }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT
          else
            if [ -n "${{ inputs.target }}" ]; then
              echo "docker-image=${{ github.repository }}:${{ inputs.target }}-build" >> $GITHUB_OUTPUT
            else
              echo "docker-image=${{ github.repository }}:final-build" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6.0.1
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Azure Login (OIDC)
        if: inputs.push == true
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        if: inputs.push == true
        run: az acr login --name ${{ inputs.acr-name }}

      - name: Docker release
        id: docker-release
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          # The full job depends on release creation, so we can directly push          
          push: ${{ inputs.push }}
          target: release
          tags: ${{ steps.validate-and-set-outputs.outputs.docker-image }}
          labels: ${{ inputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,name=gha-cache
          